# 推论统计
推论统计（或称统计推断，Statistical inference），指统计学中，研究如何根据样本数据去推断总体数量特征的方法。 它是在对样本数据进行描述的基础上，对统计总体的未知数量特征做出以概率形式表述的推断。更概括地说， 是在一段有限的时间内，通过对一个随机过程的观察来进行推断的。统计学中，统计推断与描述统计相对应。

推论统计(Statistical inferences)是借助抽样调查，从局部推断总体，以对不肯定的事物做出决策的一种统计。 有总体参数估计与假设检验两种。前者以一次性抽样实验为依据，对整个总体的某个数字特征做出估计。后者则是对 某种假设进行检验，根据计算结果推断所做的假设是否可以接受。如平均数、标准差、相关系数、回归系数等特征的 总体估计及差异显著性检验。推断统计的理论基础是概率论，它更多地需要借助抽样理论与方法。
## 参数估计与假设检验

参数估计背后的思想是通过对从总体中抽取的样本进行统计显著性检验(如t检验)，为研究人员提供关于总体的统计推断。 最常用的就是t检验，其参数检验是基于W.S.Gosset的t统计量，该统计数据假设变量来自正态总体。t检验统计量中的总体均值是已知的。 这种分布称为t分布，其形状与正态分布类似，即钟形曲线。t检验用于检验那些样本小于30的样本比正态分布要好， 在大样本上做的和正态分布一样好。

假设检验(Hypothesis test)过去也叫做显著性检验(Significance test)，是利用小概率反证法思想，从问题的对立面(H0 
 )出发， 间接判断解决问题(H1 
 )是否成立。即在假设H0 
 成立的条件下，计算检验统计量(Test static)，然后根据P 
 值(P-value)来判断。

## 统计量与标准误
样本是总体的代表和反映，也是统计推断的依据，为了对总体的分布或数字特征进行各种统计推断，还需要对样本作加工处理， 把样本中应关心的事物和信息集中起来，针对不同的问题构造出样本的不同函数(如均值，方差，极差，标准差，中位数，众数等)，这种样本的函数我们称其为统计量。

样本统计量的标准差即为标准误(Stand error,SE)，反映了抽样的统计量的离散程度或误差大小。如样本均数的标准差也称为均数标准误 (Stand error of mean, SEM)，反映了样本均数的离散程度。

# t 分布
若某一随机变量X服从总体均数为μ，总体标标准差为σ的正态分布N(μ，σ2)，通过u变换(也称Z变换)可将一般正态分布 转化为标准正态分布N(0，12)，即u分布（也称Z分布）。同理，若样本含量为n的样本均数  
ˉ
X
  服从总体均数为μ， 总体标准差为σ 
ˉ
x
 的正态分布N(μ，σ
2
ˉ
x
 
)，则可通过u变换(
ˉ
X
 −μ
σ 
ˉ
x
 
 
)将其转换为标准正态分布。 但是，实际中总体标准差( σ 
ˉ
x
  )是未知的，所以用均数标准误的估计值（S 
ˉ
x
 =
S
√
n
 
，其中S为样本标准差）代替， 这就使得(
ˉ
X
 −μ
S 
ˉ
x
 
 
)不再是标准正态分布，而是服从t-分布（t-distribution）， 即：
t=
ˉ
X
 −μ
S 
ˉ
x
 
 
=
ˉ
X
 −μ
S
√
n
 
 

t-分布 对应的概率密度函数是：
f(x)=
Γ(
v+1
2
 
)
√
vπ
Γ(
v
2
 
)
 
(1+
x2
v
 
)
−v+1
2
 

其中Γ是伽马函数(Gamma function)，v是自由度(Degree of freedom，df)。

自由度(df)在数学上只能自由取值的变量个数，如X+Y+Z=1，有3个变量，但是能够自由取值的自由两个，故其自由度v=2。 在统计学中，自由度计算方式为：
v=n−m

其中n为计算某一统计量是用到的数据个数，m为计算该统计量是用到的其他独立统计量个数。比如根据肿瘤位置，大小，组织活检，生化指标 判断肿瘤的类型是A，也可能是B，这里有n=4个独立的信息，和m=2个估计，所以自由度就是df=4−2=2。一般的希望估计（推测）的越可靠， 当然是自由度越大越好了。

t分布是一簇曲线，其形态变化与n（即其自由度）大小有关。自由度n越小，t分布曲线越低平；自由度n越大，t分布曲线越接近标准正态分布（u分布） 曲线，当自由度无限大时，t分布就成了正态分布。

